-- require'autocmd'
require'settings'
require'packer-setup'
require'plugins'
require'keybindings'
require'colorscheme'
require'plugins.nvimtree'
require'plugins.cmp'
require'lsp'
-- require'plugins.treesitter'
require'plugins.telescope'
